---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulong25-prod-wrk-deployment
  labels:
    username: vulong25
    env: prod
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vulong25-prod-wrk
  template:
    metadata:
      labels:
        app: vulong25-prod-wrk
        username: vulong25
        env: prod
    spec:
      containers:
        - name: vulong25-prod-wrk
          image: vulong2505/final-wrk:latest
          imagePullPolicy: Always
          command: ["python3"]
          args: ["worker.py"]
          env:
            - name: REDIS_IP
              value: "10.244.5.147"
            - name: WORKER_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
...