---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulong25-prod-db-deployment
  labels:
    username: vulong25
    env: prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulong25-prod-db
  template:
    metadata:
      labels:
        app: vulong25-prod-db
        username: vulong25
        env: prod
    spec:
      containers:
        - name: vulong25-prod-db
          image: vulong2505/final-db:latest
          imagePullPolicy: Always
          command: ["redis-server"]
          volumeMounts:
          - name: vulong25-prod-db-pvc
            mountPath: "/data"
      volumes:
      - name: vulong25-prod-db-pvc
        persistentVolumeClaim:
          claimName: vulong25-prod-db-pvc
...