---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vulong25-prod-db-pvc
  labels:
    env: prod
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
...